// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Authorized bool   `json:"authorized"`
	Method     string `json:"method"`
	Reconnect  bool   `json:"reconnect"`
}

type User struct {
	UID      int    `json:"uid"`
	Username string `json:"username"`
	Active   bool   `json:"active"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Method   string `json:"method"`
}
